import ManageSender from "./Layouts/smsmodule/ManageSender";
import CreateTemplate from "./Layouts/smsmodule/CreateTemplete";
import ManageEntity from "./Layouts/smsmodule/ManageEntity";
import Shop from "./components/Icons/Shop";
import ManageUsers from "./Layouts/Users/ManageUsers";
import SignIn from "./Layouts/auth/SignIn";

const routes = [
  // {
  //   type: "collapse",
  //   name: "Dashboard",
  //   key: "dashboard",
  //   route: "/dashboard",
  //   icon: <Shop size="12px" />,
  //   component: <Dashboard />,
  //   noCollapse: true,
  // },
  {
    type: "collapse",
    name: "Signin",
    key: "signin",
    route: "/signin",
    icon: <Shop size="12px" />,
    component: <SignIn />,
    noCollapse: true,
  },
  {
    type: "collapse",
    name: "manage Entites",
    key: "manageentites",
    route: "/manageentites",
    icon: <Shop size="12px" />,
    component: <ManageEntity />,
    noCollapse: false,
  },
  {
    type: "collapse",
    name: "Managesender",
    key: "managesender",
    route: "/managesender",
    icon: <Shop size="12px" />,
    component: <ManageSender />,
    noCollapse: true,
  },
  {
    type: "collapse",
    name: "Create Templete",
    key: "createtemplete",
    route: "/createtemplete",
    icon: <Shop size="12px" />,
    component: <CreateTemplate />,
    noCollapse: true,
  },

  {
    type: "collapse",
    name: "manage user",
    key: "manageusers",
    route: "/manageusers",
    icon: <Shop size="12px" />,
    component: <ManageUsers />,
    noCollapse: false,
  },
  // {
  //   type: "collapse",
  //   name: "Tables",
  //   key: "tables",
  //   route: "/tables",
  //   icon: <Office size="12px" />,
  //   component: <Tables />,
  //   noCollapse: true,
  // },
  // {
  //   type: "collapse",
  //   name: "Billing",
  //   key: "billing",
  //   route: "/billing",
  //   icon: <CreditCard size="12px" />,
  //   component: <Billing />,
  //   noCollapse: true,
  // },
  // {
  //   type: "collapse",
  //   name: "Virtual Reality",
  //   key: "virtual-reality",
  //   route: "/virtual-reality",
  //   icon: <Cube size="12px" />,
  //   component: <VirtualReality />,
  //   noCollapse: true,
  // },
  // {
  //   type: "collapse",
  //   name: "RTL",
  //   key: "rtl",
  //   route: "/rtl",
  //   icon: <Settings size="12px" />,
  //   component: <RTL />,
  //   noCollapse: true,
  // },
  // { type: "title", title: "Account Pages", key: "account-pages" },
  // {
  //   type: "collapse",
  //   name: "Profile",
  //   key: "profile",
  //   route: "/profile",
  //   icon: <CustomerSupport size="12px" />,
  //   component: <Profile />,
  //   noCollapse: true,
  // },
  // {
  //   type: "collapse",
  //   name: "Sign In",
  //   key: "sign-in",
  //   route: "/authentication/sign-in",
  //   icon: <Document size="12px" />,
  //   component: <SignIn />,
  //   noCollapse: true,
  // },
  // {
  //   type: "collapse",
  //   name: "Sign Up",
  //   key: "sign-up",
  //   route: "/authentication/sign-up",
  //   icon: <SpaceShip size="12px" />,
  //   component: <SignUp />,
  //   noCollapse: true,
  // },
];

export default routes;
